services:
  rsud-amri-tambunan-admin:
    container_name: rsud-amri-tambunan-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - fanscosa-rsud-amri-tambunan-admin-network
    mem_limit: 512m   # Maksimal RAM 512 MB
    cpus: 0.5         # Maksimal 50% dari 1 core CPU

networks:
  fanscosa-rsud-amri-tambunan-admin-network:
    external: true
